### ISSUE TITLE
SITE_PASSWORD setting is invalid

### ISSUE THREAD

**Issue by Xyfuture** [ddiu8081/chatgpt-demo#362]
### Describe the bug

commit : [ae5b625](https://github.com/ddiu8081/chatgpt-demo/commit/ae5b6251545acddcfa74ac332aa230c484a6cbfd)
用docker-compose部署,设置了SITE_PASSWORD变量,但是打开后直接能访问,没有输密码的环节
环境变量设置如下
![image](https://user-images.githubusercontent.com/49277529/231183863-929a6817-3daa-46c1-a2ba-bbe9c59afdd5.png)

### Reproduction

docker-compose up -d

### System Info

```Shell
commit : ae5b625
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Apache9** [comment]
不过前端我是真不懂，扫了扫代码也没看出来最后 docker 镜像里那个 all.xxx.mjs 是哪些文件拼出来的，里面的内容具体咋生成的，所以我也不知道应该改哪。。。

https://github.com/ddiu8081/chatgpt-demo/commit/8e5b4973b75d11bb80b641cb9afcea64e92000f5

看这个 commit，docker-env-replace.sh 一开始就是这么写的，你可以试试把这里改成 `({}).SITE_PASSWORD` 看是不是就好了

**Comment by yzh990918** [comment]
Try creating a `.env` file first and then modify the `docker-compose.yml` if using docker-compose.
```yml
version: '3'

services:
  chatgpt-demo:
    image: ddiu8081/chatgpt-demo:latest
    container_name: chatgpt-demo
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .env:/usr/src/.env
```
Run `docker compose build .` then run `docker compose up -d`.
